export  let data = [
    {
        id:1,
        countryOfOrigin:'USA',
        manufacturer:'blistein',
        manufacturerPrefix:'bil',
        mpn:1234567,
        title:'lorem impsum dolor sit',
        markets:'ebay, amazon',
        marketsUPC:'',
        bundle:17254294656,
        supliers:'Yes',
        totalQTY:'Key Stock',
        mapPrice:243,
        minPrice:876,
        maxPrice:876,
        standartPrice:876,
        salePrice:876,
        condition:'New',
        image:'https://',
        flad:'Bil-test',
        messages:14,
        listing:8,
        lastUpdate:'31.11.17',
        views:2345,
        convertion:23457,
        sold:34567,
        cases:34567,
        impression:35,
    },
    {
        id:2,
        countryOfOrigin:'USA',
        manufacturer:'blistein',
        manufacturerPrefix:'bil',
        mpn:1234567,
        title:'lorem impsum dolor sit',
        markets:'ebay, amazon',
        marketsUPC:'',
        bundle:17254294656,
        supliers:'Yes',
        totalQTY:'Key Stock',
        mapPrice:243,
        minPrice:876,
        maxPrice:876,
        standartPrice:876,
        salePrice:876,
        condition:'New',
        image:'https://',
        flad:'Bil-test',
        messages:14,
        listing:8,
        lastUpdate:'31.11.17',
        views:2345,
        convertion:23457,
        sold:34567,
        cases:34567,
        impression:35,
    },
    {
        id:3,
        countryOfOrigin:'USA',
        manufacturer:'blistein',
        manufacturerPrefix:'bil',
        mpn:1234567,
        title:'lorem impsum dolor sit',
        markets:'ebay, amazon',
        marketsUPC:'',
        bundle:17254294656,
        supliers:'Yes',
        totalQTY:'Key Stock',
        mapPrice:243,
        minPrice:876,
        maxPrice:876,
        standartPrice:876,
        salePrice:876,
        condition:'New',
        image:'https://',
        flad:'Bil-test',
        messages:14,
        listing:8,
        lastUpdate:'31.11.17',
        views:2345,
        convertion:23457,
        sold:34567,
        cases:34567,
        impression:35,
    },
]
